### ISSUE TITLE
publish bin so that it can be easily used by other editors

### ISSUE THREAD

**Issue by prabirshrestha** [rcjsuen/dockerfile-language-server-nodejs#134]
I'm working on the language server provider plugin for vim and would like to have a binary so that npm install would just work.

Would it be possible to publish a bin file so when I run `npm install -g dockerfile-language-server-nodejs`, I can run the server by running `docker-langserver --stdio`?

**Comment by rcjsuen** [comment]
This is certainly something that can be considered. I will have to do some research to see how difficult this would be.

Do you have a workaround that you can use for the time being, @prabirshrestha?

**Comment by prabirshrestha** [comment]
It should be very simple to implement this. You would need is to expose the `bin` setting in package.json.

Add this to your package.json and after running `npm install -g dockerfile-language-server-nodejs`, we should then be able to use `docker-langserver --stdio`. `docker-langserver` will be the name of the executable.

```
    "bin": {
        "docker-langserver": "lib/server.js"
    }
```

You can read a tutorial about this at http://markmarkoh.com/nodejs-npm-and-executables/

**Comment by rcjsuen** [comment]
The `lib/server.js` method did not work so I ended up creating a `bin/docker-langserver` file instead.

Please use version 0.0.4 of the npm module and not 0.0.3.

**Comment by prabirshrestha** [comment]
Thanks. It works.
