### ISSUE TITLE
Two ARG completion items are displayed when snippets are not supported

### ISSUE THREAD

**Issue by rcjsuen** [rcjsuen/dockerfile-language-server-nodejs#137]
When snippets are enabled, two different `ARG` completion items are displayed. One is for `ARG name` and the other is for `ARG name=defaultValue`. This makes sense because the user can choose which one to use.

However, if snippets are disabled, both completion items perform the same thing and only append `ARG` into the document. From a coding point of view this makes both completion items effectively identical so only one `ARG` completion item should be displayed if `snippetSupport` is `false`.

**Comment by prabirshrestha** [comment]
Cloud you publish the new package version to npm?

**Comment by rcjsuen** [comment]
@prabirshrestha I have published v0.0.5 to npm.

**Comment by prabirshrestha** [comment]
Thanks. It works.
