### ISSUE TITLE
implement textDocument/didSave

### ISSUE THREAD

**Issue by prabirshrestha** [rcjsuen/dockerfile-language-server-nodejs#165]
In vim-lsp I automatically didSave when a file is saved. Would be good if this was implemented.

https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#textDocument_didSave

**Comment by rcjsuen** [comment]
@prabirshrestha I don't understand. The protocol [states the following](https://github.com/Microsoft/language-server-protocol/blob/e1ecd6a23a80735a1a7dc2abe3b684a7032e651e/protocol.md#textDocument_didSave):

> The document save notification is sent from the client to the server when the document was saved in the client.

This is a notification from the client to the server. I don't think this is something for the language server to implement.

**Comment by prabirshrestha** [comment]
My bad. I was sending a request instead of notification and was getting not supported error by the server. Sorry for the noise.

**Comment by rcjsuen** [comment]
@prabirshrestha Thank you for checking, Prabir. :)

You should also check if the language server you are connected to is actually interested in that event before sending it. Check out the `ServerCapabilities.textDocumentSync` section in the protocol.

The `ServerCapabilities.textDocumentSync.save` setting may not be set. In that case, you don't want to waste resources sending something over the wire if the language server you are talking to isn't even interested in the that event.

**Comment by prabirshrestha** [comment]
Seems like I need to update `vim-lsp`. Filed a bug to track this. https://github.com/prabirshrestha/vim-lsp/issues/29. That for the details.

**Comment by rcjsuen** [comment]
@prabirshrestha Actually, I think I might have been wrong about when a client should be sending that notification to the server. Sorry about that.

I think a client might have to _always_ send the notification unless the `ServerCapabilities.textDocumentSync.save` value is defined and set to `false`. [Version 2.x of the protocol](https://github.com/Microsoft/language-server-protocol/blob/e1ecd6a23a80735a1a7dc2abe3b684a7032e651e/versions/protocol-2-x.md) had the `textDocument/didSave` notification but it wasn't possible for the server to declare whether it was interested in the event or not so I think the expectation is that the notification will always be sent to the server unless it explicitly says it isn't interested in it.

For example, my language server only sets a `TextDocumentSyncKind` number for its `ServerCapabilities.textDocumentSync` [property](https://github.com/rcjsuen/dockerfile-language-server-nodejs/blob/139d2c9a84d8ed5584fa69954a4da6e7f6dce4f9/src/server.ts#L61) but VS Code still sends me `textDocument/didSave` notifications although it doesn't include the document's text in the notification.

**Comment by rcjsuen** [comment]
@prabirshrestha Actually, `ServerCapabilities.textDocumentSync.save` won't be set to `false` because it's a `SaveOptions` object and not a `boolean`. So I think the correct behaviour would be for the client to not send the notification only if that property is undefined.

I could be wrong of course so you may want to [open an issue](https://github.com/Microsoft/language-server-protocol/issues) and ask for clarifications.

Sorry for all the confusion that I'm causing!

**Comment by prabirshrestha** [comment]
Filed an issue at https://github.com/Microsoft/language-server-protocol/issues/288.
