### ISSUE TITLE
cannot connect server with socket

### ISSUE THREAD

**Issue by kyurdakok** [rcjsuen/dockerfile-language-server-nodejs#178]
i'm trying to play with this language server but i've got a problem

cloned the repo build with the command ```npm run build``` and runned the server ``` node .\out\src\server.js --socket 4001 ``` and tried to connect with html5 web sockets server dropped with no error. 

any suggestions?

**Comment by rcjsuen** [comment]
Hi @kyurdakok, thank you for your interest in this project and for opening this bug report.

To be completely, I am not sure if the socket support is working properly. Please see Microsoft/vscode-languageserver-node#245 and Microsoft/vscode-languageserver-node-example#37.

**Comment by rcjsuen** [comment]
Looks like this problem has supposedly been fixed upstream per the closing of Microsoft/vscode-languageserver-node#245. Will have to do some testing to verify the fix.

**Comment by rcjsuen** [comment]
I believe the fix that upstream has delivered is incorrect. I have posted my findings [on Microsoft/vscode-languageserver-node#245](https://github.com/Microsoft/vscode-languageserver-node/issues/245#issuecomment-334919916).

**Comment by rcjsuen** [comment]
Looks like the fix was actually fine. The client needs to be the one listening for connections instead of trying to connect to the language server. The language server will attempt to connect to the specified port so the client needs to listen for connections on the specified port before starting up the language server.

**Comment by rcjsuen** [comment]
@kyurdakok Socket support should now be working with dd63ee989ec3b1364ec31b9dd4172a7f325020db. Don't forget to update your dependencies with `npm install`. You can refer to the [README.md](https://github.com/rcjsuen/dockerfile-language-server-nodejs/blob/dd63ee989ec3b1364ec31b9dd4172a7f325020db/README.md) file for some sample code that shows how to talk to the language server using sockets.

Thank you again for bringing this bug to our attention!

**Comment by rcjsuen** [comment]
I have published version 0.0.9 to npm which includes this fix.
