### ISSUE TITLE
Linter flags COPY's closing JSON bracket as an invalid argument

### ISSUE THREAD

**Issue by chrisdias** [rcjsuen/dockerfile-language-server-nodejs#217]
Testing 0.0.14...

This is the default dockerfile the extension creates for Node. Note the error which is not present in previous versions:

![image](https://user-images.githubusercontent.com/1487073/38157658-c43811d2-343d-11e8-9349-522bf8066889.png)

and, according to the error message, it should be correct since it ends in a `/`.

**Comment by chrisdias** [comment]
i'm wondering if we should revert `0.0.14` as i want to publish the extension today...

**Comment by rcjsuen** [comment]
Reproduced and tracked by rcjsuen/dockerfile-utils#29. Thanks for the bug report!
