### ISSUE TITLE
Releases should be tagged on Docker Hub

### ISSUE THREAD

**Issue by chrismwendt** [rcjsuen/dockerfile-language-server-nodejs#222]
The only tag is `latest`, which updates on every commit and makes it difficult for you to make breaking changes if you need to.

**Comment by rcjsuen** [comment]
Thanks for opening this, @chrismwendt. I've tagged and pushed `0.0.11`, `0.0.12`, `0.0.13`, `0.0.14`, `0.0.15`, `0.0.16`, and `0.0.17` to Docker Hub. The Dockerfile was added to the repository in the 0.0.11 release so I figured I would start there.

If you'd also like the older releases tagged and pushed, please let me know! Thank you again for your interest in this project!
