### ISSUE TITLE
failed to build: Invalid containerPort:

### ISSUE THREAD

**Issue by nikhilgupta00008** [rcjsuen/dockerfile-language-server-nodejs#235]
I am trying to setup docker using Env variables it is giving me a Invalid containerport error. but if i am working with same file with hardcoded values it is working fine. Please find attached docker , docker-compose and env files

[Dockerfile.zip](https://github.com/rcjsuen/dockerfile-language-server-nodejs/files/3099991/Dockerfile.zip)

**Comment by rcjsuen** [comment]
Hi, @nikhilgupta00008. Thank you very much for your bug report. Based on your files, I have pinpointed the error and have opened up rcjsuen/dockerfile-utils#57 to address this.
