### ISSUE TITLE
Please consider switching diagnostics to warning by default

### ISSUE THREAD

**Issue by akurtakov** [rcjsuen/dockerfile-language-server-nodejs#237]
Being able to configure level is nice but most people just stick to defaults so would you please consider bumping to warning so they are always visible and clients can downgrade them if they want?

**Comment by rcjsuen** [comment]
Hi, @akurtakov. Can you be more specific about what you are asking for? You would like all errors downgraded to warnings?

I do have configurable defaulting to `ValidationSeverity.WARNING`.

https://github.com/rcjsuen/dockerfile-language-server-nodejs/blob/ba930e8c052ef21e716acb0266cef64d3067f70c/src/server.ts#L252-L260

**Comment by akurtakov** [comment]
Ah, so it must be smth on my end. With https://git.eclipse.org/r/c/146811/ I get autocomplete working properly but no diagnostics. I'll have to investigate further.

**Comment by rcjsuen** [comment]
@akurtakov Wow, very cool! My [dream from two years ago](https://www.eclipse.org/lists/linuxtools-dev/msg04214.html) may become a reality!

Let me know if I can help!

**Comment by akurtakov** [comment]
Well, testing the patch and telling me what did I do wrong would be appreciated :)

**Comment by rcjsuen** [comment]
@akurtakov Oof! You got me! I'll see if I can spare some cycles somewhere... :thinking:
