### ISSUE TITLE
Unknown instruction error within a string

### ISSUE THREAD

**Issue by rchl** [rcjsuen/dockerfile-language-server-nodejs#240]
I would guess this shouldn't be an error as it's not a docker instruction but part of the string?
![dockerfile](https://user-images.githubusercontent.com/153197/80226361-8e39a380-864c-11ea-9d1f-5ba76a6deac4.png)

**Comment by rcjsuen** [comment]
@rchl Can you attach your full Dockerfile here? Thanks.

**Comment by rchl** [comment]
I actually can't reproduce this on demand.
It could be related to another issue that triggered before that - https://github.com/sublimelsp/LSP-dockerfile/issues/3#issuecomment-619067826 so we will investigate that one first.

**Comment by rcjsuen** [comment]
@rchl My guess is that it's related to the ordering of content changes. There may be a bug in the synchronization so it it's parsing text that's not actually in the opened editor... 🤔

**Comment by rchl** [comment]
I can't reproduce it anymore. With or without the fix for https://github.com/sublimelsp/LSP/issues/982. I'll come back if I see it again.
