### ISSUE TITLE
The server does not launch.

### ISSUE THREAD

**Issue by cotigao** [rcjsuen/dockerfile-language-server-nodejs#241]
I checked out the code and ran all the necessary build and installs on a linux (ubuntu 19.04) machine.
Ran the following command to launch the server.

```
docker-langserver --socket=3000
```

The moment I run the above command, the server just exits on its own. 

```
> tsc --version
Version 3.9.5
> node --version
v12.16.3
```

**Comment by rcjsuen** [comment]
@cotigao Did you [open up port 3000](https://github.com/rcjsuen/dockerfile-language-server-nodejs/blob/fa6f8516ebd3afd6f4d1d43e6c118954223656f0/README.md#sockets) so that it is listening for connections?

**Comment by cotigao** [comment]
@rcjsuen oops! Guess I got the understanding wrong. I thought the LSP server would be listening on 3000 and the client (IDE) would connect to it.  So turns out the client (IDE) needs to start a server that's listening, which means the LSP server (that acts like a client )connects to the client (IDE, which is a server listening on port 300). Please correct me if I have got it wrong, if you feel

**Comment by rcjsuen** [comment]
> So turns out the client (IDE) needs to start a server that's listening, which means the LSP server (that acts like a client )connects to the client (IDE, which is a server listening on port 300).

@cotigao That is correct.

**Comment by cotigao** [comment]
@rcjsuen If I may ask, is there a specific reason to have it that way?

**Comment by rcjsuen** [comment]
@cotigao See https://github.com/microsoft/vscode-languageserver-node/issues/245#issuecomment-336054699.

**Comment by cotigao** [comment]
@rcjsuen Thanks! That seems a bit counter-intuitive. But then I guess it is fine because LSP does not mandate on what medium is to be used for the server and client to establish the connection and  to exchange messages.  

We can close this issue. Thanks for the prompt respone.

**Comment by rcjsuen** [comment]
> We can close this issue. Thanks for the prompt respone.

No problem. Happy to help.
