### ISSUE TITLE
Fails to execute when using a custom npm prefix

### ISSUE THREAD

**Issue by jzelinskie** [rcjsuen/dockerfile-language-server-nodejs#252]
My .npmrc uses a custom prefix to install binaries into $XDG_DATA_HOME:

```npmrc
prefix=${XDG_DATA_HOME}/node
```

This breaks docker-langserver because it's using a relative import to execute the server:

```sh
cat $XDG_DATA_HOME/node/bin/docker-langserver

   1   │ #!/usr/bin/env node
   2   │ /* --------------------------------------------------------------------------------------------
   3   │  * Copyright (c) Remy Suen. All rights reserved.
   4   │  * Licensed under the MIT License. See License.txt in the project root for license information.
   5   │  * ------------------------------------------------------------------------------------------ */
   6   │ require("../lib/server");
```

**Comment by rcjsuen** [comment]
@jzelinskie Thank you for your bug report. I'll do some searching to see what the right solution is here.

**Comment by rcjsuen** [comment]
@jzelinskie I looked at both [Mocha](https://github.com/mochajs/mocha/blob/97b84708afb42e552cb906a54f9f2aa2e6a98ba4/bin/_mocha) and [TypeScript](https://github.com/microsoft/TypeScript/blob/dbf3cd38214cbf84a1c39ab631b495bc40b46b41/bin/tsc) and they both seem to do the same thing here.

Do you have an example of an open source project that works for your setup?

**Comment by jzelinskie** [comment]
It was forever ago that I reported this and I can't seem to reproduce this on my new laptop.

```
$ cat .npmrc
prefix=${XDG_DATA_HOME}/node
$ echo $XDG_DATA_HOME
/Users/jzelinskie/.local/share
$ which docker-langserver
/Users/jzelinskie/.local/share/node/bin/docker-langserver
$ docker-langserver --stdio
^C
```

**Comment by rcjsuen** [comment]
@jzelinskie Thanks for getting back to us. Have a nice day!
