### ISSUE TITLE
keep-git-dir flag not recognized

### ISSUE THREAD

**Issue by tydra-wang** [rcjsuen/dockerfile-language-server-nodejs#265]
```
ADD --keep-git-dir=true <git ref> <dir>
```

got an error: `Unknown flag: keep-git-dir`

dockerfile references:
https://docs.docker.com/engine/reference/builder/#adding-a-git-repository-add-git-ref-dir

**Comment by rcjsuen** [comment]
Thanks for raising this issue. Will take a look...

**Comment by rcjsuen** [comment]
The actual work has been completed and was tracked by https://github.com/rcjsuen/dockerfile-utils/issues/117. Will keep this issue open for tracking the work to adopt the change in the language server itself.

**Comment by rcjsuen** [comment]
This is now fixed in the latest 0.11.0 release of the language server. Thank you for bringing this issue to our attention, @tydra-wang.
